// source: src/Service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.grpc.SalaryLoan', null, global);
goog.exportSymbol('proto.grpc.SalaryLoanList', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc.SalaryLoan = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc.SalaryLoan, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.grpc.SalaryLoan.displayName = 'proto.grpc.SalaryLoan';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc.SalaryLoanList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.grpc.SalaryLoanList.repeatedFields_, null);
};
goog.inherits(proto.grpc.SalaryLoanList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.grpc.SalaryLoanList.displayName = 'proto.grpc.SalaryLoanList';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc.SalaryLoan.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc.SalaryLoan.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc.SalaryLoan} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc.SalaryLoan.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    aconumber: jspb.Message.getFieldWithDefault(msg, 2, 0),
    amount: jspb.Message.getFieldWithDefault(msg, 3, 0),
    term: jspb.Message.getFieldWithDefault(msg, 4, 0),
    loanid: jspb.Message.getFieldWithDefault(msg, 5, 0),
    validthru: (f = msg.getValidthru()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    creationdate: (f = msg.getCreationdate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc.SalaryLoan}
 */
proto.grpc.SalaryLoan.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc.SalaryLoan;
  return proto.grpc.SalaryLoan.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc.SalaryLoan} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc.SalaryLoan}
 */
proto.grpc.SalaryLoan.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setClientid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAconumber(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAmount(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTerm(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLoanid(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setValidthru(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreationdate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc.SalaryLoan.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc.SalaryLoan.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc.SalaryLoan} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc.SalaryLoan.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getAconumber();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getTerm();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getLoanid();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getValidthru();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCreationdate();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 clientId = 1;
 * @return {number}
 */
proto.grpc.SalaryLoan.prototype.getClientid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.grpc.SalaryLoan} returns this
 */
proto.grpc.SalaryLoan.prototype.setClientid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 acoNumber = 2;
 * @return {number}
 */
proto.grpc.SalaryLoan.prototype.getAconumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.grpc.SalaryLoan} returns this
 */
proto.grpc.SalaryLoan.prototype.setAconumber = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 amount = 3;
 * @return {number}
 */
proto.grpc.SalaryLoan.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.grpc.SalaryLoan} returns this
 */
proto.grpc.SalaryLoan.prototype.setAmount = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 term = 4;
 * @return {number}
 */
proto.grpc.SalaryLoan.prototype.getTerm = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.grpc.SalaryLoan} returns this
 */
proto.grpc.SalaryLoan.prototype.setTerm = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 loanId = 5;
 * @return {number}
 */
proto.grpc.SalaryLoan.prototype.getLoanid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.grpc.SalaryLoan} returns this
 */
proto.grpc.SalaryLoan.prototype.setLoanid = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional google.protobuf.Timestamp validThru = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.grpc.SalaryLoan.prototype.getValidthru = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.grpc.SalaryLoan} returns this
*/
proto.grpc.SalaryLoan.prototype.setValidthru = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.grpc.SalaryLoan} returns this
 */
proto.grpc.SalaryLoan.prototype.clearValidthru = function() {
  return this.setValidthru(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.grpc.SalaryLoan.prototype.hasValidthru = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Timestamp creationDate = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.grpc.SalaryLoan.prototype.getCreationdate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.grpc.SalaryLoan} returns this
*/
proto.grpc.SalaryLoan.prototype.setCreationdate = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.grpc.SalaryLoan} returns this
 */
proto.grpc.SalaryLoan.prototype.clearCreationdate = function() {
  return this.setCreationdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.grpc.SalaryLoan.prototype.hasCreationdate = function() {
  return jspb.Message.getField(this, 7) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.grpc.SalaryLoanList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc.SalaryLoanList.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc.SalaryLoanList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc.SalaryLoanList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc.SalaryLoanList.toObject = function(includeInstance, msg) {
  var f, obj = {
    salaryloanList: jspb.Message.toObjectList(msg.getSalaryloanList(),
    proto.grpc.SalaryLoan.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc.SalaryLoanList}
 */
proto.grpc.SalaryLoanList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc.SalaryLoanList;
  return proto.grpc.SalaryLoanList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc.SalaryLoanList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc.SalaryLoanList}
 */
proto.grpc.SalaryLoanList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.grpc.SalaryLoan;
      reader.readMessage(value,proto.grpc.SalaryLoan.deserializeBinaryFromReader);
      msg.addSalaryloan(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc.SalaryLoanList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc.SalaryLoanList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc.SalaryLoanList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc.SalaryLoanList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSalaryloanList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.grpc.SalaryLoan.serializeBinaryToWriter
    );
  }
};


/**
 * repeated SalaryLoan salaryLoan = 1;
 * @return {!Array<!proto.grpc.SalaryLoan>}
 */
proto.grpc.SalaryLoanList.prototype.getSalaryloanList = function() {
  return /** @type{!Array<!proto.grpc.SalaryLoan>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.grpc.SalaryLoan, 1));
};


/**
 * @param {!Array<!proto.grpc.SalaryLoan>} value
 * @return {!proto.grpc.SalaryLoanList} returns this
*/
proto.grpc.SalaryLoanList.prototype.setSalaryloanList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.grpc.SalaryLoan=} opt_value
 * @param {number=} opt_index
 * @return {!proto.grpc.SalaryLoan}
 */
proto.grpc.SalaryLoanList.prototype.addSalaryloan = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.grpc.SalaryLoan, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.grpc.SalaryLoanList} returns this
 */
proto.grpc.SalaryLoanList.prototype.clearSalaryloanList = function() {
  return this.setSalaryloanList([]);
};


goog.object.extend(exports, proto.grpc);
